### ISSUE TITLE
Unison

### ISSUE THREAD

**Issue by ar4s-eth** [benrayfield/wikibinator203#1]
Hi Ben,

stumbled upon your repos and I think this might be right up your alley: 
https://github.com/unisonweb/unison

(if hadn’t already heard of it, of course!)

**Comment by benrayfield** [comment]
From the website, it seems to have some things in common with Wikibinator (and maybe some with Urbit), including "Unison references code by hash instead of by name", but it seems to be too stateful to be a replacement for Wikibinator. "Say where you want computations to run and it happens". For example, wikibinator, by design, cant know that the network layer exists, cant know that specific network addresses exist, and doesnt "run" anything. Wikibinator doesnt have IO, such as: helloWorld _ = printLine "Hello World". Wikibinator doesnt have a Remote keyword, like in "distributed : Seq k Nat ->{Remote} Nat", since by design even a change of a single bit is defined to work both remotely and locally everywhere or anywhere and to sync without knowing if its remote or local. Its 100% cache of the space of all possibilities, and all actions are cache sync. Also, does unison have anything like a godel-numbering (such as all binary-forest pairs with no data in the leafs)?

This quote shows what my problem is with state, pretty well...

http : '{IO, Exception} Response
http _ =
  host = HostName "unison-lang.org"
  web = Authority None host None
  path = Path.root / "learn"
  uri = Uri https (Some web) path Query.empty None
  req = Request.get uri
  handle request req with Http.handler

With state, "authority" is needed. Without state, it can be more decentralized.

Also I'm going for in browser deployment mostly, with a little localhost servers for peer to peer networking. If i cant just instantly drop it in a dir and compute lambdaA lambdaB -> lambdaC, that really decreases the chance of "going viral". The most networking-like thing I have a use for, in systems like these, are (publicKeyA timeRange question)->answer, where publicKeyA contains a verifier of a sig answer etc, and it doesnt even matter if the answer comes before the question in a time paradox, wont break anything.
